### ISSUE TITLE
About the Pytorch checkpoint

### ISSUE THREAD

**Issue by ngoductuanlhp** [cvlab-kaist/locotrack#6]
Hi @Seokju-Cho,

Thank you for your great work and congrats for the acceptance to ECCV! I tried running the evaluation using your pytorch implementation, however, when I load the `locotrack_base.ckpt` there is an error "KeyError: "filename 'storages' not found"", but I successfully load and run the `locotrack_small.ckpt`. So could you double-check and re-upload ckpt of the base model? 

Thank you.

**Comment by Seokju-Cho** [comment]
Thank you for your interest in our work and for bringing the error to our attention. We have updated the checkpoint to the correct file.
